train_dataset: mini
train_dataset_args: {split: train}

val_dataset: mini
val_dataset_args: {split: test}


model_args: 
    encoder: wrn
load_encoder: ./save/encoder_mini_wrn_Cos_fs_test_256_rot_dropout/max_v_acc.pth

n_way: 5
n_shot: 5
n_query: 15
train_batches: 800

save_epoch: 1
max_epoch: 50
optimizer: sgd
optimizer_args: {lr: 0.01, weight_decay: 5.e-4}

# freeze_bn: True
# freeze_encoder: True
visualize_datasets: True
