train_dataset: mini
train_dataset_args: {split: train}

val_dataset: mini
val_dataset_args: {split: test}


model_args:
    encoder: wrn
    classifier: Cos
    classifier_n_classes: 64

batch_size: 128
max_epoch: 120
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [60,80,100]}

save_epoch: 1
visualize_datasets: true
